### ISSUE TITLE
Support wake on AC and wake on LAN

### ISSUE THREAD

**Issue by jackpot51** [system76/firmware-open#109]
First, we should verify how this was done in previous firmware.

**Comment by crawfxrd** [comment]
The Insyde H2O BIOS enables Wake on PME, but it is not configurable on the oryp5.

**Comment by jackpot51** [comment]
We discussed wake on AC before, and decided it was not necessary with the addition of wake on LAN. So I think this is done

**Comment by tomkinsc** [comment]
Joining this conversation a few years late, we would value wake-on-AC. We have a bit of an unusual use case: we tend to deploy System76 systems in always-on configurations to accompany scientific instruments in developing countries with unreliable electric grids. Laptops work well for settings like this because in addition to whatever UPS and generator are backing the power, the built-in battery buffers power too. Unfortunately there are times when the internal battery, UPS, and generator all run out. In such circumstances it would be helpful for the systems to be able to wake automatically when power returns. Wake-on-LAN does not fulfill the need because we would have to add another device with wake-on-AC to serve as a watchdog and issue the wake-on-LAN packet.
