### ISSUE TITLE
`oryp9/10` HDMI

### ISSUE THREAD

**Issue by thomas-zimmerman** [system76/firmware-open#407]
Much like https://github.com/system76/firmware-open/issues/387

System does not boot to OS if plugged into HDMI<>HDMI external monitor.

If HDMI is plugged at login screen, additional screen works as expected. If plugged in while session is active, additional screen is ignored.

**Comment by brs17** [comment]
Do you have an idea when this issue was first and most recently reported?

**Comment by VWY-github** [comment]
I have this problem about 40% of the time. Seems to be hit or miss. Much more likely to get to the OS if *not* connected to external monitor via hdmi (but sometimes it does work for me).
Hoping for a new bios version soonn (wasnt  a new version announced just today?) that might cure some ills.
Also have frequent issues with crypto, but that may be a different story

**Comment by VWY-github** [comment]
When will new firmware be pushed out and automatically installable?

**Comment by ahoneybun** [comment]
@VWY-github once it has passed QA, you will get a notification once it is available.

**Comment by n-hebert** [comment]
Is anyone assigned to this one, @ahoneybun ? GitHub doesn't have anyone listed right now.

I reported a very similar this one (one may be a duplicate) via #391 and am very much looking to assist with squashing it in any way possible (r&d, impl, debug, whatever's appropriate). 
I'm very new to this area of the stack, but a veteran of software, is it fair to say this problem is in the EC rom? That's where I suspect it to be and was planning on digging through old commits, as we know this broke between 2021 and now.

I would love to collaborate with whoever is working on this!

**Comment by leviport** [comment]
Oryp9 and oryp10 updates have been released.

**Comment by n-hebert** [comment]
hey @leviport , thanks for updating those. The Oryp8 also has the same bug, so a couple questions there:
1. Any update coming for the Oryp8?
2.  should we open a new issue for it or is #391 good enough to represent this?
Cheers

**Comment by leviport** [comment]
#391 should be fine for tracking that. We'll have updates for oryp8 as soon as we can.

**Comment by marcin-rzeznicki** [comment]
And how is that actually solved? For me it's still hit-miss to boot with HDMI plugged in
